# Generated by Django 3.0 on 2022-01-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_content',
            new_name='blog_content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_title',
            new_name='blog_title',
        ),
    ]
